export const store = {
  users: [
    {
      id: 'u1',
      name: 'Alex Rivera',
      email: 'alex@example.com',
      password: 'password123',
      bookmarks: [12, 9]
    },
  ],
  settings: {
    theme: 'light',
    language: 'en',
  },
  topics: [
    { id: 't1', name: 'Technology', description: 'AI, cloud and product innovation.' },
    { id: 't2', name: 'Cybersecurity', description: 'Threats, policy and zero-trust updates.' },
    { id: 't3', name: 'Startups', description: 'Funding, scale-ups and market movement.' },
  ],
  articles: [
    {
      id: 12,
      category: 'TECHNOLOGY',
      source: 'TechCrunch',
      savedAgo: '2 hours ago',
      readMinutes: 5,
      imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop',
      title: 'EU AI Act: What changes for product teams',
      summary: 'A practical view on compliance impact for software teams.',
      content:
        'The EU AI Act introduces risk-based obligations. Teams should classify systems, document datasets and establish human oversight where required.',
    },
    {
      id: 11,
      category: 'FINANCE',
      source: 'Bloomberg',
      savedAgo: '6 hours ago',
      readMinutes: 8,
      imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
      title: 'How edge AI is moving into mainstream apps',
      summary: 'On-device models are becoming practical for modern products.',
      content:
        'Edge AI helps reduce latency and preserve privacy by processing data locally. Tooling is improving for mobile and desktop deployment.',
    },
    {
      id: 10,
      category: 'LIFESTYLE',
      source: 'NY Times',
      savedAgo: 'yesterday',
      readMinutes: 12,
      imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=1200&auto=format&fit=crop',
      title: '10 healthiest superfoods to add to your daily diet in 2024',
      summary: 'A practical list of nutrient-rich food choices.',
      content: 'Balanced nutrition patterns are easier to keep when meals are planned around whole ingredients and simple weekly routines.',
    },
    {
      id: 9,
      category: 'SCIENCE',
      source: 'NASA News',
      savedAgo: '3 days ago',
      readMinutes: 4,
      imageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?q=80&w=1200&auto=format&fit=crop',
      title: 'Telescope reveals atmospheric water vapor on distant exoplanet',
      summary: 'New measurements improve understanding of exoplanet climates.',
      content: 'Observations from modern telescopes continue to improve atmospheric models and long-term exoplanet characterization.',
    },
    {
      id: 8,
      category: 'TECHNOLOGY',
      source: 'The Verge',
      savedAgo: '5 days ago',
      readMinutes: 10,
      imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop',
      title: 'Quantum computing and the next frontier in global security',
      summary: 'Why quantum policy is now a board-level topic.',
      content: 'Security teams are evaluating post-quantum migration paths while regulators and standards bodies accelerate guidance.',
    },
    {
      id: 7,
      category: 'FINANCE',
      source: 'Reuters',
      savedAgo: '1 week ago',
      readMinutes: 6,
      imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop',
      title: 'Central banks signal policy shifts as inflation cools',
      summary: 'Markets react to new guidance and rate expectations.',
      content: 'Forward-looking indicators suggest policy decisions will remain data dependent as inflation gradually normalizes.',
    },
  ],
};
